/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiseaseNameIndexRouteImport } from './routes/disease/$name/index'
import { Route as DiseaseNameTypeIndexRouteImport } from './routes/disease/$name/$type/index'

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseNameIndexRoute = DiseaseNameIndexRouteImport.update({
  id: '/disease/$name/',
  path: '/disease/$name/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseNameTypeIndexRoute = DiseaseNameTypeIndexRouteImport.update({
  id: '/disease/$name/$type/',
  path: '/disease/$name/$type/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/search': typeof SearchRoute
  '/statistics': typeof StatisticsRoute
  '/disease/$name/': typeof DiseaseNameIndexRoute
  '/disease/$name/$type/': typeof DiseaseNameTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/search': typeof SearchRoute
  '/statistics': typeof StatisticsRoute
  '/disease/$name': typeof DiseaseNameIndexRoute
  '/disease/$name/$type': typeof DiseaseNameTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/search': typeof SearchRoute
  '/statistics': typeof StatisticsRoute
  '/disease/$name/': typeof DiseaseNameIndexRoute
  '/disease/$name/$type/': typeof DiseaseNameTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chatbot'
    | '/search'
    | '/statistics'
    | '/disease/$name/'
    | '/disease/$name/$type/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chatbot'
    | '/search'
    | '/statistics'
    | '/disease/$name'
    | '/disease/$name/$type'
  id:
    | '__root__'
    | '/'
    | '/chatbot'
    | '/search'
    | '/statistics'
    | '/disease/$name/'
    | '/disease/$name/$type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatbotRoute: typeof ChatbotRoute
  SearchRoute: typeof SearchRoute
  StatisticsRoute: typeof StatisticsRoute
  DiseaseNameIndexRoute: typeof DiseaseNameIndexRoute
  DiseaseNameTypeIndexRoute: typeof DiseaseNameTypeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease/$name/': {
      id: '/disease/$name/'
      path: '/disease/$name'
      fullPath: '/disease/$name/'
      preLoaderRoute: typeof DiseaseNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease/$name/$type/': {
      id: '/disease/$name/$type/'
      path: '/disease/$name/$type'
      fullPath: '/disease/$name/$type/'
      preLoaderRoute: typeof DiseaseNameTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatbotRoute: ChatbotRoute,
  SearchRoute: SearchRoute,
  StatisticsRoute: StatisticsRoute,
  DiseaseNameIndexRoute: DiseaseNameIndexRoute,
  DiseaseNameTypeIndexRoute: DiseaseNameTypeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
